version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    restart: on-failure
    volumes:
      - ./nginx/inde.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - 80:80

  geonetwork:
    image: ghcr.io/sgb-cprm/geonetwork:3.10.2
    restart: on-failure
    environment:
      - GEONETWORK_DATA_DIR=${GEONETWORK_DATA_DIR}
      - GEONETWORK_LUCENE_DIR=${GEONETWORK_DATA_DIR}
      - GEONETWORK_DB_TYPE=postgis
      - GEONETWORK_DB_HOST=${POSTGRES_HOST}
      - GEONETWORK_DB_PORT=${POSTGRES_PORT}
      - GEONETWORK_DB_DATABASE=${GEONETWORK_DATABASE} 
      - GEONETWORK_DB_USERNAME=${GEONETWORK_USER}
      - GEONETWORK_DB_PASSWORD=${GEONETWORK_PASSWORD}
    volumes:
      - geonetwork-data:${GEONETWORK_DATA_DIR}
      - geonetwork-index:${GEONETWORK_LUCENE_DIR}
    depends_on:
      - db

  geoserver:
    image: kartoza/geoserver:${GEOSERVER_VERSION}
    restart: on-failure
    environment:
      # Diretório de dados
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      # Cota de disco para cache
      - DB_BACKEND=POSTGRES
      - HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${GEOSERVER_DATABASE}
      - POSTGRES_USER=${GEOSERVER_USER}
      - POSTGRES_PASS=${GEOSERVER_PASSWORD}
    volumes:
      - geoserver-data:${GEOSERVER_DATA_DIR}
    depends_on:
      - db    
  
  db:
    image: postgis/postgis:13-3.2-alpine
    restart: on-failure
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres@INDE
      - PGDATA=${POSTGRES_DATA_DIR}
      # Geoserver
      - GEOSERVER_DATABASE=${GEOSERVER_DATABASE}
      - GEOSERVER_USER=${GEOSERVER_USER}
      - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD}
      # Geonetwork
      - GEONETWORK_DATABASE=${GEONETWORK_DATABASE}
      - GEONETWORK_USER=${GEONETWORK_USER}
      - GEONETWORK_PASSWORD=${GEONETWORK_PASSWORD}
    volumes:
      - postgres-data:${POSTGRES_DATA_DIR}
      - ./postgis/initdb.sh:/docker-entrypoint-initdb.d/20-init-inde-databases.sh:ro

volumes:
  geonetwork-data:
  postgres-data:
  geoserver-data:
  geonetwork-index:
