version: '3.7'

services:
  geonetwork:
    image: ghcr.io/sgb-cprm/geonetwork:${GEONETWORK_VERSION}
    build:
      context: geonetwork
      args:
        - GEONETWORK_VERSION=${GEONETWORK_VERSION}