version: '3.7'

services:
  nginx:
    image: nginx:1.22.1-alpine
    restart: on-failure
    volumes:
      - ./nginx/inde.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - 80:80

  geonetwork:
    image: ghcr.io/sgb-cprm/geonetwork:3.10.2
    restart: on-failure
    environment:
      - GEONETWORK_DATA_DIR=${GEONETWORK_DATA_DIR}
      - GEONETWORK_LUCENE_DIR=${GEONETWORK_DATA_DIR}
      - GEONETWORK_DB_TYPE=postgis
      - GEONETWORK_DB_HOST=${POSTGRES_HOST}
      - GEONETWORK_DB_PORT=${POSTGRES_PORT}
      - GEONETWORK_DB_DATABASE=${GEONETWORK_DATABASE} 
      - GEONETWORK_DB_USERNAME=${GEONETWORK_USER}
      - GEONETWORK_DB_PASSWORD=${GEONETWORK_PASSWORD}
    volumes:
      - geonetwork-data:${GEONETWORK_DATA_DIR}
      - geonetwork-index:${GEONETWORK_LUCENE_DIR}
    depends_on:
      - db

  geoserver:
    image: kartoza/geoserver:${GEOSERVER_VERSION}
    restart: on-failure
    environment:
      # Diretório de dados
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      # Cota de disco para cache
      - DB_BACKEND=POSTGRES
      - HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${GEOSERVER_DATABASE}
      - POSTGRES_USER=${GEOSERVER_USER}
      - POSTGRES_PASS=${GEOSERVER_PASSWORD}
    volumes:
      - geoserver-data:${GEOSERVER_DATA_DIR}
    depends_on:
      - db

  geohealthcheck:
    image: geopython/geohealthcheck:${GEOHEALTHCHECK_VERSION}
    restart: on-failure
    environment:
      - SCRIPT_NAME=/geohealthcheck
      - SQLALCHEMY_DATABASE_URI=postgresql://${GEOHEALTHCHECK_USER}:${GEOHEALTHCHECK_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${GEOHEALTHCHECK_DATABASE}
      - GHC_RUNNER_IN_WEBAPP=False
      - GHC_NOTIFICATIONS=${GHC_NOTIFICATIONS}
      - GHC_NOTIFICATIONS_VERBOSITY=${GHC_NOTIFICATIONS_VERBOSITY}
      - GHC_ADMIN_EMAIL=${GHC_ADMIN_EMAIL}
      - GHC_NOTIFICATIONS_EMAIL=${GHC_NOTIFICATIONS_EMAIL}
      - GHC_SMTP_SERVER=${GHC_SMTP_SERVER}
      - GHC_SMTP_PORT=${GHC_SMTP_PORT}
      - GHC_SMTP_TLS=${GHC_SMTP_TLS}
      - GHC_SMTP_SSL=${GHC_SMTP_SSL}
      - GHC_SMTP_USERNAME=${GHC_SMTP_USERNAME}
      - GHC_SMTP_PASSWORD=${GHC_SMTP_PASSWORD}
      - GHC_LOG_LEVEL=${GHC_LOG_LEVEL}
    depends_on:
      - db
    ports:
      - 81:80

  geohealthcheck-runner:
    image: geopython/geohealthcheck:${GEOHEALTHCHECK_VERSION}
    restart: on-failure
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${GEOHEALTHCHECK_USER}:${GEOHEALTHCHECK_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${GEOHEALTHCHECK_DATABASE}
      - GHC_RUNNER_IN_WEBAPP=False
      - GHC_NOTIFICATIONS=${GHC_NOTIFICATIONS}
      - GHC_NOTIFICATIONS_VERBOSITY=${GHC_NOTIFICATIONS_VERBOSITY}
      - GHC_ADMIN_EMAIL=${GHC_ADMIN_EMAIL}
      - GHC_NOTIFICATIONS_EMAIL=${GHC_NOTIFICATIONS_EMAIL}
      - GHC_SMTP_SERVER=${GHC_SMTP_SERVER}
      - GHC_SMTP_PORT=${GHC_SMTP_PORT}
      - GHC_SMTP_TLS=${GHC_SMTP_TLS}
      - GHC_SMTP_SSL=${GHC_SMTP_SSL}
      - GHC_SMTP_USERNAME=${GHC_SMTP_USERNAME}
      - GHC_SMTP_PASSWORD=${GHC_SMTP_PASSWORD}
      - GHC_LOG_LEVEL=${GHC_LOG_LEVEL}
    depends_on:
      - db
    entrypoint:
      - /run-runner.sh  
  
  db:
    image: postgis/postgis:13-3.2-alpine
    restart: on-failure
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres@INDE
      - PGDATA=${POSTGRES_DATA_DIR}
      # Geoserver
      - GEOSERVER_DATABASE=${GEOSERVER_DATABASE}
      - GEOSERVER_USER=${GEOSERVER_USER}
      - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD}
      # Geonetwork
      - GEONETWORK_DATABASE=${GEONETWORK_DATABASE}
      - GEONETWORK_USER=${GEONETWORK_USER}
      - GEONETWORK_PASSWORD=${GEONETWORK_PASSWORD}
      # GeoHeathCheck
      - GEOHEALTHCHECK_DATABASE=${GEOHEALTHCHECK_DATABASE}
      - GEOHEALTHCHECK_USER=${GEOHEALTHCHECK_USER}
      - GEOHEALTHCHECK_PASSWORD=${GEOHEALTHCHECK_PASSWORD}
    volumes:
      - postgres-data:${POSTGRES_DATA_DIR}
      - ./postgis/initdb.sh:/docker-entrypoint-initdb.d/20-init-inde-databases.sh:ro

volumes:
  geonetwork-data:
  geonetwork-index:
  postgres-data:
  geoserver-data:
